name: blog cd

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install ssh-key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan -H "dev.devecor.cn" >> ~/.ssh/known_hosts
      
      - name: Publish blog
        continue-on-error: true
        run: |
          ssh root@dev.devecor.cn "mkdir -p ${{ secrets.BLOG_HOME }}"
          rsync -r $PWD/cn/devecor/blog/ root@dev.devecor.cn:${{ secrets.BLOG_HOME }}blog@next
          ssh root@dev.devecor.cn "
            rm ${{ secrets.BLOG_HOME }}blog/*;
            cp ${{ secrets.BLOG_HOME }}blog@next/* ${{ secrets.BLOG_HOME }}blog;
            rm -r ${{ secrets.BLOG_HOME }}blog@next;
          "

      - name: Delete ssh-key
        run: rm ~/.ssh/id_ed25519
