name: blog cd

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Publish
        run: |
          git clone https://github.com/clarkwang/passh.git
          gcc ./passh/passh.c -o passhe
          ./passhe -p '${{ secrets.TENCENT_CLOUD_TOKEN }}' scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r $PWD/cn/devecor/blog/ ubuntu@devecor.cn:${{ secrets.BLOG_HOME }}blognew
          ./passhe -p '${{ secrets.TENCENT_CLOUD_TOKEN }}' ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@devecor.cn "rm -r ${{ secrets.BLOG_HOME }}blog; mv ${{ secrets.BLOG_HOME }}blognew ${{ secrets.BLOG_HOME }}blog"
